# Generated by Django 3.2.1 on 2021-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordings',
            name='test',
            field=models.CharField(default='test', max_length=225),
        ),
    ]
